import Link from "next/link";
import { Bookmark, ChevronRight, Settings, UserRound } from "lucide-react";
import { demoProfile } from "@/lib/demo/screens";
import { DemoBanner, ScreenHeader } from "@/components/ui/screen";

export function ProfileScreen() {
  const profile = demoProfile;
  return <main id="main-content"><ScreenHeader title="Profile" back="/" action={<Link href="/profile/edit" className="inline-flex min-h-11 items-center rounded-full bg-secondary px-4 py-2 text-sm font-medium">Edit</Link>} /><div className="space-y-8 p-5"><DemoBanner>Fictional demo profile. You are not signed in.</DemoBanner><section className="space-y-3 text-center"><div className="mx-auto flex size-24 items-center justify-center rounded-full bg-secondary text-primary"><UserRound className="size-12" aria-hidden="true" /></div><h2 className="text-2xl font-bold">{profile.fullName}</h2><p className="text-sm text-muted-foreground">Universiti Malaya <span className="ml-1 rounded bg-accent px-2 py-1 text-xs font-semibold text-primary">UM Student (demo)</span></p><p className="text-sm text-muted-foreground">{profile.faculty}<br />{profile.programme}<br />Year {profile.year}</p></section><section className="space-y-3"><h2 className="field-label uppercase tracking-wide">Bio</h2><p>{profile.bio}</p></section><section className="space-y-3 border-t border-secondary pt-6"><h2 className="field-label uppercase tracking-wide">Interests</h2><div className="flex flex-wrap gap-2">{profile.interests.map(interest => <span key={interest} className="rounded-full bg-primary px-4 py-2 text-sm font-semibold text-white">{interest}</span>)}</div></section><section className="space-y-3 border-t border-secondary pt-6"><h2 className="field-label uppercase tracking-wide">Activity</h2><div className="grid grid-cols-2 gap-3">{[[profile.hosted, "Activities Hosted"], [profile.joined, "Activities Joined"]].map(([count, label]) => <div key={label} className="rounded-lg border border-secondary p-5"><p className="text-2xl font-bold">{count}</p><p className="helper-text">{label}</p></div>)}</div></section><div className="divide-y divide-secondary border-y border-secondary">{[{href:"/saved-activities",label:"Saved Activities",Icon:Bookmark},{href:"/settings",label:"Settings",Icon:Settings}].map(({href,label,Icon}) => <Link key={href} href={href} className="flex items-center gap-3 py-4"><Icon className="size-5 text-muted-foreground" /><span className="flex-1 font-medium">{label}</span><ChevronRight className="size-4 text-muted-foreground" /></Link>)}</div><Link href="/sign-in" className="block text-center text-sm text-primary underline">Preview sign in</Link></div></main>;
}
